services:
  - type: web
    name: nebulaChest
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: APP_URL
        # This will be filled in after deployment
        value: "https://minechesegame.onrender.com"
      - key: DATABASE_URL
        # This should be a connection string to your PostgreSQL database
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        # Telegram Bot Token
        value: "7442658111:AAF15N3rZg_S3SX7vD5gIOIcuicuTYDn3fA"
      - key: GAME_WALLET_ADDRESS
        # TON Wallet Address for the game
        value: "UQANJGqFrn96wqLaDQz4O2pVcTt1m-IRpf6aH-i-KpamjONa"
